var numbers = new Array(101);
var label = numbers.length;
for (var i = 1; i < label; i++) {
    console.log(i);
}

// One liner I found -- for(var x=1;x<101;x++)document.write((((x%3?'':'FIZZ')+(x%5?'':'BUZZ'))||x)+'<br>');
/* or
let numbers = [
    { int: 1, str: 'one' },
    { int: 2, str: 'two' },
    { int: 3, str: 'three' },
    { int: 4, str: 'four' },
    { int: 5, str: 'five' },
    { int: 6, str: 'six' },
    { int: 7, str: 'seven' },
    { int: 8, str: 'eight' },
    { int: 9, str: 'nine' },
    { int: 10, str: 'ten' },
    { int: 11, str: 'eleven' },
    { int: 12, str: 'twelve' },
    { int: 13, str: 'thirteen' },
    { int: 14, str: 'fourteen' },
    { int: 15, str: 'fifteen' },
    { int: 16, str: 'sixteen' },
    { int: 17, str: 'seventeen' },
    { int: 18, str: 'eighteen' },
    { int: 19, str: 'nineteen' },
    { int: 20, str: 'twenty' },
    { int: 21, str: 'twenty-one' },
    { int: 22, str: 'twenty-two' },
    { int: 23, str: 'twenty-three' },
    { int: 24, str: 'twenty-four' },
    { int: 25, str: 'twenty-five' },
    { int: 26, str: 'twenty-six' },
    { int: 27, str: 'twenty-seven' },
    { int: 28, str: 'twenty-eight' },
    { int: 29, str: 'twenty-nine' },
    { int: 30, str: 'thirty' },
    { int: 31, str: 'thirty-one' },
    { int: 32, str: 'thirty-two' },
    { int: 33, str: 'thirty-three' },
    { int: 34, str: 'thirty-four' },
    { int: 35, str: 'thirty-five' },
    { int: 36, str: 'thirty-six' },
    { int: 37, str: 'thirty-seven' },
    { int: 38, str: 'thirty-eight' },
    { int: 39, str: 'thirty-nine' },
    { int: 40, str: 'forty' },
    { int: 41, str: 'forty-one' },
    { int: 42, str: 'forty-two' },
    { int: 43, str: 'forty-three' },
    { int: 44, str: 'forty-four' },
    { int: 45, str: 'forty-five' },
    { int: 46, str: 'forty-six' },
    { int: 47, str: 'forty-seven' },
    { int: 48, str: 'forty-eight' },
    { int: 49, str: 'forty-nine' },
    { int: 50, str: 'fifty' },
    { int: 51, str: 'fifty-one' },
    { int: 52, str: 'fifty-two' },
    { int: 53, str: 'fifty-three' },
    { int: 54, str: 'fifty-four' },
    { int: 55, str: 'fifty-five' },
    { int: 56, str: 'fifty-six' },
    { int: 57, str: 'fifty-seven' },
    { int: 58, str: 'fifty-eight' },
    { int: 59, str: 'fifty-nine' },
    { int: 60, str: 'sixty' },
    { int: 61, str: 'sixty-one' },
    { int: 62, str: 'sixty-two' },
    { int: 63, str: 'sixty-three' },
    { int: 64, str: 'sixty-four' },
    { int: 65, str: 'sixty-five' },
    { int: 66, str: 'sixty-six' },
    { int: 67, str: 'sixty-seven' },
    { int: 68, str: 'sixty-eight' },
    { int: 69, str: 'sixty-nine' },
    { int: 70, str: 'seventy' },
    { int: 71, str: 'seventy-one' },
    { int: 72, str: 'seventy-two' },
    { int: 73, str: 'seventy-three' },
    { int: 74, str: 'seventy-four' },
    { int: 75, str: 'seventy-five' },
    { int: 76, str: 'seventy-six' },
    { int: 77, str: 'seventy-seven' },
    { int: 78, str: 'seventy-eight' },
    { int: 79, str: 'seventy-nine' },
    { int: 80, str: 'eighty' },
    { int: 81, str: 'eighty-one' },
    { int: 82, str: 'eighty-two' },
    { int: 83, str: 'eighty-three' },
    { int: 84, str: 'eighty-four' },
    { int: 85, str: 'eighty-five' },
    { int: 86, str: 'eighty-six' },
    { int: 87, str: 'eighty-seven' },
    { int: 88, str: 'eighty-eight' },
    { int: 89, str: 'eighty-nine' },
    { int: 90, str: 'ninety' },
    { int: 91, str: 'ninety-one' },
    { int: 92, str: 'ninety-two' },
    { int: 93, str: 'ninety-three' },
    { int: 94, str: 'ninety-four' },
    { int: 95, str: 'ninety-five' },
    { int: 96, str: 'ninety-six' },
    { int: 97, str: 'ninety-seven' },
    { int: 98, str: 'ninety-eight' },
    { int: 99, str: 'ninety-nine' },
    { int: 100, str: 'one-hundred' }],

    module.exports = numbers;

    or

    */


